### ISSUE TITLE
Why xrange?

### ISSUE THREAD

**Issue by t184256** [Covald/NSU-3-course#1]
Why xrange?

https://github.com/Covald/NSU-3-course-/blob/f1ebdc4628a3e53454d7c32db348a29897ef79f0/First%20block/(14).py#L3

**Comment by Covald** [comment]
I am trying to understand and do how this article - https://habr.com/ru/post/142825/. At the moment, I have not yet fully understood the solution. 

I think this is not the last version of this task.

**Comment by t184256** [comment]
It's from Python 2 times, when `range` wasn't as lazy as it is now.

Good luck with the course.

**Comment by Covald** [comment]
Hmm, intersting (I just started studying python and English :) )

Thank you)
